### ISSUE TITLE
[helm charts] Add parameters for Redis

### ISSUE THREAD

**Issue by slevenet** [qameta/testops-deploy-helm-chart#31]
## Context

Add new parameters to clients and cloud charts:

```
      ALLURE_REDIS_SESSIONTTL: 10d
```

ALLURE_REDIS_SESSIONTTL - ttl for redis sessions (Time after which the session tie expired of an inactive user expires) see [#7996](https://github.com/qameta/allure-server/issues/7996)

---

By default (if not set): 
ALLURE_REDIS_SESSIONTTL - 30d,

**Comment by cheshi-mantu** [comment]
@alexey-bogdanov discussed with Sergey
let's set default TTL
```
ALLURE_REDIS_SESSIONTTL: 10d
```

and omit adding 
```
ALLURE_REDIS_SLOBUCKETS
```
latter is more like useful for our cloud and for the end users we'll use defaults

**Comment by Frodox** [comment]
Добавляем и в облачный чарт (cloud) и в клиентский (in-house)

Параметры одинаковые:

- `ALLURE_REDIS_SESSIONTTL: 10d`
- `ALLURE_REDIS_SLOBUCKETS: 1ms, 10ms, 50ms, 100ms`

**Comment by cheshi-mantu** [comment]
> Let's add it into both cloud and client chards (in-house)
> 
> with same parameters:
> 
> * `ALLURE_REDIS_SESSIONTTL: 10d`
> * `ALLURE_REDIS_SLOBUCKETS: 1ms, 10ms, 50ms, 100ms`

let's don't
I don't need this in clients' config. It'll use the default 1ms, 10ms, 50ms, 100ms and env.open if required something custom upon request.
We don't need this as it'll overload the chart as we had in version 4
